#!/usr/bin/env python3
"""Bump the Homebrew tap and Scoop bucket after a CLI release
(docs/cli.md § Distribution, docs/deployment.md § CLI release assets).

Renders Formula/kano-proxy.rb (tap) and bucket/kano-proxy.json (scoop) from
the release's SHA256SUMS and pushes each to its repo with TAP_PUSH_TOKEN.

Env: VERSION (no leading v), SUMS_PATH, TAP_PUSH_TOKEN.
"""

from __future__ import annotations

import os
import subprocess
import sys
import tempfile
from pathlib import Path

REPO = "yufeng-kano/kano-proxy"
TAP_REPO = "yufeng-kano/homebrew-tap"
BUCKET_REPO = "yufeng-kano/scoop-bucket"

TARGETS = {
    "mac_arm": "aarch64-apple-darwin",
    "mac_x64": "x86_64-apple-darwin",
    "linux_x64": "x86_64-unknown-linux-musl",
    "linux_arm": "aarch64-unknown-linux-musl",
    "win_x64": "x86_64-pc-windows-msvc",
}


def load_sums(path: Path) -> dict[str, str]:
    sums: dict[str, str] = {}
    for line in path.read_text().splitlines():
        parts = line.split()
        if len(parts) >= 2:
            sums[parts[1].lstrip("*")] = parts[0]
    return sums


def sum_for(sums: dict[str, str], version: str, target: str, ext: str) -> str:
    name = f"kano-proxy-{version}-{target}.{ext}"
    if name not in sums:
        raise SystemExit(f"SHA256SUMS has no entry for {name}")
    return sums[name]


def formula(version: str, sums: dict[str, str]) -> str:
    base = f"https://github.com/{REPO}/releases/download/v{version}"

    def block(target: str) -> tuple[str, str]:
        return (f"{base}/kano-proxy-{version}-{target}.tar.gz", sum_for(sums, version, target, "tar.gz"))

    mac_arm = block(TARGETS["mac_arm"])
    mac_x64 = block(TARGETS["mac_x64"])
    linux_arm = block(TARGETS["linux_arm"])
    linux_x64 = block(TARGETS["linux_x64"])
    return f'''# Auto-generated by release CI ({REPO}) — do not edit by hand.
class KanoProxy < Formula
  desc "Official kano-proxy CLI: expose local LLM servers as providers"
  homepage "https://github.com/{REPO}"
  version "{version}"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "{mac_arm[0]}"
      sha256 "{mac_arm[1]}"
    else
      url "{mac_x64[0]}"
      sha256 "{mac_x64[1]}"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "{linux_arm[0]}"
      sha256 "{linux_arm[1]}"
    else
      url "{linux_x64[0]}"
      sha256 "{linux_x64[1]}"
    end
  end

  def install
    bin.install "kano-proxy"
  end

  test do
    assert_match version.to_s, shell_output("#{{bin}}/kano-proxy --version")
  end
end
'''


def manifest(version: str, sums: dict[str, str]) -> str:
    base = f"https://github.com/{REPO}/releases/download/v{version}"
    name = f"kano-proxy-{version}-{TARGETS['win_x64']}.zip"
    import json

    return (
        json.dumps(
            {
                "version": version,
                "description": "Official kano-proxy CLI: expose local LLM servers as providers",
                "homepage": f"https://github.com/{REPO}",
                "license": "MIT",
                "architecture": {
                    "64bit": {
                        "url": f"{base}/{name}",
                        "hash": sum_for(sums, version, TARGETS["win_x64"], "zip"),
                    }
                },
                "bin": "kano-proxy.exe",
                "checkver": {"github": f"https://github.com/{REPO}"},
                "autoupdate": {
                    "architecture": {
                        "64bit": {
                            "url": f"{base.replace(version, '$version')}/kano-proxy-$version-{TARGETS['win_x64']}.zip"
                        }
                    }
                },
            },
            indent=2,
        )
        + "\n"
    )


def push(repo: str, rel_path: str, content: str, version: str, token: str) -> None:
    with tempfile.TemporaryDirectory() as tmp:
        url = f"https://x-access-token:{token}@github.com/{repo}.git"
        subprocess.run(["git", "clone", "--depth", "1", url, tmp], check=True, capture_output=True)
        target = Path(tmp) / rel_path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content)
        env = os.environ | {
            "GIT_AUTHOR_NAME": "release-ci",
            "GIT_AUTHOR_EMAIL": "ci@users.noreply.github.com",
            "GIT_COMMITTER_NAME": "release-ci",
            "GIT_COMMITTER_EMAIL": "ci@users.noreply.github.com",
        }
        subprocess.run(["git", "-C", tmp, "add", rel_path], check=True, env=env)
        diff = subprocess.run(["git", "-C", tmp, "diff", "--cached", "--quiet"], env=env)
        if diff.returncode == 0:
            print(f"{repo}: already at {version}", file=sys.stderr)
            return
        subprocess.run(
            ["git", "-C", tmp, "commit", "-m", f"kano-proxy {version}"],
            check=True,
            env=env,
            capture_output=True,
        )
        subprocess.run(["git", "-C", tmp, "push"], check=True, env=env, capture_output=True)
        print(f"{repo}: bumped to {version}", file=sys.stderr)


def main() -> None:
    version = os.environ.get("VERSION", "").strip().lstrip("v")
    sums_path = os.environ.get("SUMS_PATH", "").strip()
    token = os.environ.get("TAP_PUSH_TOKEN", "").strip()
    if not version or not sums_path:
        raise SystemExit("VERSION and SUMS_PATH are required")
    if not token:
        # Skip-with-warning by contract (docs/deployment.md): the assets are
        # already on the Release; re-run this job after adding the secret.
        print("TAP_PUSH_TOKEN is not set — skipping tap/scoop bump", file=sys.stderr)
        return
    sums = load_sums(Path(sums_path))
    # Warn-and-continue per repo: a missing tap/bucket repo (or a token that
    # cannot reach it) must not fail the release — the assets are already
    # attached, and this job can be re-run once the repo/secret exists.
    for repo, rel_path, content in (
        (TAP_REPO, "Formula/kano-proxy.rb", formula(version, sums)),
        (BUCKET_REPO, "bucket/kano-proxy.json", manifest(version, sums)),
    ):
        try:
            push(repo, rel_path, content, version, token)
        except subprocess.CalledProcessError as e:
            print(f"warning: could not bump {repo} ({e}) — re-run this job after fixing the repo/secret", file=sys.stderr)


if __name__ == "__main__":
    main()
